services:
  - type: web
    name: ai-model-comparison
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: MAX_TOKENS
        value: 512
      - key: TEMPERATURE
        value: 0.7
    plan: free 